service: medium-backend

plugins:
  - serverless-offline
custom:
  serverless-offline:
    noPrependStageInUrl: true
provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: ap-south-1
functions:
  app:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: "{proxy+}"
          method: any
package:
  exclude:
    - src/**
    - .git/**
    - README.md
    - .env
    - node_modules/**
    - node_modules.zip
